# Generated by Django 6.0 on 2025-12-04 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'مجاني'), ('basic', 'أساسي'), ('premium', 'مميز'), ('vip', 'VIP')], max_length=20, unique=True, verbose_name='اسم الخطة')),
                ('display_name', models.CharField(max_length=50, verbose_name='الاسم المعروض')),
                ('price_yearly', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر السنوي')),
                ('max_products', models.PositiveIntegerField(help_text='اكتب 0 لغير محدود', verbose_name='الحد الأقصى للمنتجات')),
                ('can_upload_images', models.BooleanField(default=False, verbose_name='رفع صور المنتجات')),
                ('show_prices', models.BooleanField(default=False, verbose_name='عرض الأسعار')),
                ('has_delivery_options', models.BooleanField(default=False, verbose_name='خيارات التوصيل')),
                ('featured_in_search', models.BooleanField(default=False, verbose_name='أولوية في نتائج البحث')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['price_yearly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي')], default='active', max_length=10, verbose_name='الحالة')),
                ('auto_renew', models.BooleanField(default=False, verbose_name='تجديد تلقائي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='directory.business', verbose_name='المحل')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
