# Generated by Django 6.0 on 2025-12-07 14:02

import django.core.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AddField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(help_text='العنوان التفصيلي للمحل', verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(help_text='وصف تفصيلي عن المحل والخدمات المقدمة', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(default=False, help_text='تفعيل/إيقاف ظهور المحل في الموقع', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='تم التحقق من صحة المحل', verbose_name='موثّق'),
        ),
        migrations.AlterField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='يتم تحديده تلقائياً من الخريطة', max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, help_text='يُفضل صورة مربعة 500x500 بكسل', null=True, upload_to='businesses/logos/%Y/%m/', verbose_name='اللوجو'),
        ),
        migrations.AlterField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='يتم تحديده تلقائياً من الخريطة', max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='اسم المحل'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(help_text='مثال: 01234567890', max_length=15, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف مصري صحيح (مثال: 01234567890)', regex='^01[0-2,5]{1}[0-9]{8}$')], verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='business',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='عدد المشاهدات'),
        ),
        migrations.AlterField(
            model_name='business',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='رقم واتساب (اختياري)', max_length=15, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف مصري صحيح (مثال: 01234567890)', regex='^01[0-2,5]{1}[0-9]{8}$')], verbose_name='واتساب'),
        ),
        migrations.AlterField(
            model_name='business',
            name='working_hours',
            field=models.TextField(blank=True, help_text='مثال: السبت-الخميس: 9 صباحاً - 10 مساءً | الجمعة: 2 مساءً - 10 مساءً', verbose_name='ساعات العمل'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للفئة (اختياري)', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='مثال: fas fa-utensils', max_length=50, verbose_name='أيقونة Font Awesome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إلغاء التفعيل يخفي الفئة من الموقع', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='مثال: مطاعم ومقاهي، صيدليات، محلات ملابس', max_length=100, unique=True, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=0, help_text='رقم أصغر = يظهر أولاً', verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, help_text='معلومات عن الحي (اختياري)', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True, help_text='إلغاء التفعيل يخفي الحي من الموقع', verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(help_text='مثال: التل الكبير، الشيخ زايد، الأفنيوز', max_length=100, unique=True, verbose_name='اسم الحي'),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='الرابط'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['slug'], name='directory_b_slug_c6091d_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_active', 'is_verified'], name='directory_b_is_acti_7561dd_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['category', 'is_active'], name='directory_b_categor_6c6136_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['district', 'is_active'], name='directory_b_distric_79407c_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['-view_count'], name='directory_b_view_co_8b070f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='directory_c_slug_2e5f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active', 'order'], name='directory_c_is_acti_947875_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['slug'], name='directory_d_slug_9838a8_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['is_active'], name='directory_d_is_acti_24b6ac_idx'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='valid_latitude', violation_error_message='خط العرض يجب أن يكون بين -90 و 90'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='valid_longitude', violation_error_message='خط الطول يجب أن يكون بين -180 و 180'),
        ),
    ]
