# Generated by Django 6.0 on 2025-12-15 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_governorate_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='valid_latitude',
        ),
        migrations.RemoveConstraint(
            model_name='business',
            name='valid_longitude',
        ),
        migrations.RemoveIndex(
            model_name='district',
            name='directory_d_is_acti_24b6ac_idx',
        ),
        migrations.RenameIndex(
            model_name='governorate',
            new_name='directory_g_slug_a530e1_idx',
            old_name='dir_gov_slug',
        ),
        migrations.RenameIndex(
            model_name='governorate',
            new_name='directory_g_is_acti_c59c66_idx',
            old_name='dir_gov_active',
        ),
        migrations.AddField(
            model_name='business',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='عرض المحل في قسم المحلات المميزة', verbose_name='مميز'),
        ),
        migrations.AddField(
            model_name='business',
            name='location_url',
            field=models.URLField(blank=True, help_text='رابط موقع المحل على خرائط جوجل (اختياري)', verbose_name='رابط الموقع (Google Maps)'),
        ),
        migrations.AddField(
            model_name='business',
            name='website',
            field=models.URLField(blank=True, help_text='رابط الموقع الإلكتروني للمحل (اختياري)', verbose_name='الموقع الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', related_query_name='business', to='directory.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='business',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='businesses', related_query_name='business', to='directory.district', verbose_name='الحي'),
        ),
        migrations.AlterField(
            model_name='business',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', related_query_name='business', to=settings.AUTH_USER_MODEL, verbose_name='المالك'),
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='مثال: مطاعم ومقاهي، صيدليات، محلات ملابس', max_length=100, unique=True, verbose_name='اسم الفئة'),
        ),
        migrations.AlterField(
            model_name='district',
            name='governorate',
            field=models.ForeignKey(help_text='المحافظة التابع لها الحي', on_delete=django.db.models.deletion.PROTECT, related_name='districts', related_query_name='district', to='directory.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, help_text='مثال: التل الكبير، الشيخ زايد، الأفنيوز', max_length=100, verbose_name='اسم الحي'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['is_featured'], name='directory_b_is_feat_1960a5_idx'),
        ),
        migrations.AddIndex(
            model_name='business',
            index=models.Index(fields=['owner', 'is_active'], name='directory_b_owner_i_4e66c5_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['governorate', 'is_active'], name='directory_d_governo_0d70d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90), ('latitude__lte', 90)), ('latitude__isnull', True), _connector='OR'), name='valid_latitude', violation_error_message='خط العرض يجب أن يكون بين -90 و 90'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('longitude__gte', -180), ('longitude__lte', 180)), ('longitude__isnull', True), _connector='OR'), name='valid_longitude', violation_error_message='خط الطول يجب أن يكون بين -180 و 180'),
        ),
    ]
