# Generated by Django 6.0 on 2025-12-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_remove_business_valid_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['order', 'name'], 'verbose_name': 'حي', 'verbose_name_plural': 'الأحياء'},
        ),
        migrations.RemoveIndex(
            model_name='district',
            name='directory_d_slug_9838a8_idx',
        ),
        migrations.RemoveIndex(
            model_name='district',
            name='directory_d_governo_0d70d6_idx',
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='district',
            name='order',
            field=models.IntegerField(default=0, verbose_name='الترتيب'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='district',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='directory.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='district',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الحي'),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
