# Generated by Django 6.0 on 2025-12-15 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['governorate__order', 'governorate__name', 'order', 'name'], 'verbose_name': 'حي', 'verbose_name_plural': 'الأحياء'},
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-store', help_text='مثال: fas fa-utensils', max_length=50, verbose_name='أيقونة Font Awesome'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='district',
            name='description',
            field=models.TextField(blank=True, help_text='وصف تفصيلي للحي (اختياري)', verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='district',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', related_query_name='district', to='directory.governorate', verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='اسم الحي'),
        ),
        migrations.AlterField(
            model_name='district',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-city', help_text='مثال: fas fa-city', max_length=50, verbose_name='أيقونة Font Awesome'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('governorate', 'name')},
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['slug'], name='directory_d_slug_9838a8_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['governorate', 'is_active'], name='directory_d_governo_0d70d6_idx'),
        ),
        migrations.AddIndex(
            model_name='district',
            index=models.Index(fields=['is_active', 'order'], name='directory_d_is_acti_b562b8_idx'),
        ),
    ]
