# Generated by Django 6.0 on 2025-12-16 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_district_options_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='facebook',
            field=models.URLField(blank=True, help_text='رابط صفحة الفيسبوك (اختياري)', verbose_name='فيسبوك'),
        ),
        migrations.AddField(
            model_name='business',
            name='instagram',
            field=models.URLField(blank=True, help_text='رابط حساب الإنستجرام (اختياري)', verbose_name='إنستجرام'),
        ),
        migrations.AddField(
            model_name='business',
            name='twitter',
            field=models.URLField(blank=True, help_text='رابط حساب تويتر (اختياري)', verbose_name='تويتر'),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة تمثيلية للفئة (اختياري)', null=True, upload_to='categories/%Y/%m/', verbose_name='صورة الفئة'),
        ),
        migrations.AddField(
            model_name='governorate',
            name='image',
            field=models.ImageField(blank=True, help_text='صورة تمثيلية للمحافظة (اختياري)', null=True, upload_to='governorates/%Y/%m/', verbose_name='صورة المحافظة'),
        ),
        migrations.CreateModel(
            name='BusinessImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='businesses/images/%Y/%m/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='وصف الصورة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image', to='directory.business', verbose_name='المحل')),
            ],
            options={
                'verbose_name': 'صورة محل',
                'verbose_name_plural': 'صور المحلات',
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['business', 'is_active'], name='directory_b_busines_02693a_idx')],
            },
        ),
    ]
