# Generated by Django 6.0 on 2026-01-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0007_business_facebook_business_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='صورة عريضة للعرض في البطاقة والبانر (يُفضل 1200x400 بكسل)', null=True, upload_to='businesses/covers/%Y/%m/', verbose_name='صورة الغلاف'),
        ),
    ]
